AxaFrance/oidc-client

CONTRIBUTING.md, packages/context/README.md, readme.md
Repair links and fix some typo inside readme
=> fix(readme) typo and links

.travis.yaml
=> chore: build master branch only

readme.md
=> chore: add travis status

CONTRIBUTING.md, package-lock.json, packages/context/src/Context/AuthenticationConsumers.js, packages/context/src/OidcComponents/Authenticating.component.js, packages/context/src/OidcComponents/__snapshots__/Authenticating.component.spec.js.snap
=> fix : recompose branch test in the consumer and add doc about dev

.travis.yml
should allow to edit this variable in order to publish from build
config:
env: 
- NPM_PUBLISH_VERSION=none
=> chore(build) add user variable for releasing a specific version to npm

readme.md
=> doc: add npm version badge

packages/context/src/Services/loggerService.js
=> replacing includes by indexof

examples/context/src/Pages/Home/Home.jsx, packages/context-fetch/src/withFetchToken.js
oidcUser was not found and so the token was not transmited during the fetch
Correction with the token in the fetch call
New button on example to see token in the fetch
=> fix : Context Fetch>oidcUser transmission

readme.md
I think this is pretty straight forward.
=> Fix context example link

packages/fetch-core/package-lock.json, packages/fetch-core/package.json
chore: remove react-redux dependency
=> chore(fetch-core) remove react-redux dependency

examples/context/package.json, examples/context/src/Layout/Header.js, examples/context/src/index.js, package-lock.json, package.json, packages/context/src/Context/AuthenticationConsumers.js, packages/context/src/Context/AuthenticationContext.container.js, packages/context/src/Context/AuthenticationContext.js
OIDC context can be now disabled using a props in the container 
Close #104
=> feat(OIDC Context) add disable props on container

packages/context/src/Callback/Callback.container.js, packages/context/src/Callback/SilentCallback.component.js, packages/context/src/Callback/SilentCallback.component.spec.js, packages/context/src/Routes/OidcRoutes.js, packages/redux/src/AuthenticationCallback.js, packages/redux/src/AuthenticationSignSilentCallback.js
=> fix(context) no state found in storage

packages/context/src/Callback/Callback.container.js, packages/context/src/Context/AuthenticationConsumers.js, packages/context/src/Context/AuthenticationContext.container.js
This code fix many bugs on IE and Mozilla
=> Fix(context) component should wait user loading

packages/fetch-core/src/fetchToken.js
=> Fetch Core : Fix for header props

packages/context/README.md
=> doc : add optionnal parameter for post logout uri redirect

packages/context/README.md
=> docs: fixed a typo on AuthenticationProvider

examples/context/src/Pages/CustomCallback/CustomCallback.jsx, examples/context/src/Pages/CustomCallback/index.js, examples/context/src/index.js, examples/redux/src/ComponentOverride.js, examples/redux/src/index.js, package-lock.json, packages/context/README.md, packages/context/src/Callback/Callback.container.js, packages/context/src/Context/AuthenticationContext.container.js, packages/core/src/default-component/Callback.component.js, packages/core/src/default-component/Callback.component.spec.js, packages/core/src/default-component/__snapshots__/Callback.component.spec.js.snap, packages/core/src/default-component/index.js, packages/core/src/index.js, packages/core/src/routes/OidcRoutes.js, packages/redux/README.md, packages/redux/src/AuthenticationCallback.js, packages/redux/src/Oidc.js
The callback component was the only component that we should'nt customize
Now, for the context, or redux package, you can customize by adding a prop
=> Add callback component

examples/context/src/Router/Routes.js, packages/context/src/Context/AuthenticationContext.container.js, packages/context/src/Context/OidcEvents.js, packages/context/src/Context/OidcEvents.spec.js
If one silent signin crashes the entire app crashes
If one silent signin crashes we just lose the token.
=> fix(context): Fix silent crash

packages/context/src/Context/AuthenticationContext.container.js
=> fix(context): avoid errors on console with custom callback

examples/context/src/Pages/Dashboard/Dashboard.jsx, packages/context/README.md, packages/context/src/Context/AuthenticationConsumers.js, packages/context/src/Context/AuthenticationContext.container.js
=> feat(context): Add events in useReactOidc hook

packages/core/src/services/authenticationService.js, packages/core/src/services/authenticationService.spec.js
Replace `console.log` in `authenticationService.js` file by `oidcLog.info`
=> chore: Replace console.log by oidcLog

examples/redux/config-overrides.js
This PR fixes the redux example.
=> Overrides the react-redux dependency

examples/context/src/configuration.js, examples/redux/src/configuration.js, examples/vanilla/src/index.js, packages/context/README.md, packages/redux/README.md, packages/vanilla/README.md
=> Remove all occurences of 'triggerAuthFlow'

examples/context/src/Layout/Header.js, examples/context/src/Pages/Admin/Admin.jsx, examples/context/src/Pages/SimpleComponent/index.js, examples/context/src/Router/Routes.js, packages/context/src/reactServices/OidcSecure.spec.tsx, packages/context/src/reactServices/OidcSecure.tsx, packages/context/src/reactServices/__snapshots__/OidcSecure.spec.tsx.snap
=> fix(context): Renrender children aftersilent signin

packages/context/src/oidcContext/AuthenticationContext.provider.tsx, packages/context/src/reactServices/oidcUser.tsx
=> Fix types for AuthenticationProvider and withOidcUser

.eslintrc.js
Eslint remove overwritten property jsx-filename-extension
=> style: remove overwritten property jsx-filename-extension

examples/context/src/Layout/Header.js, packages/context/README.md, packages/context/src/oidcContext/AuthenticationContext.provider.tsx, packages/context/src/oidcContext/AuthenticationContext.tsx
=> feat: add signinSilent to useReactOidc and AuthenticationContext

.github/workflows/npm-publish.yml, packages/context/src/configurations.ts, packages/context/src/oidc/OidcProvider.tsx, packages/context/src/oidc/core/default-component/Callback.component.tsx, packages/context/src/oidc/core/default-component/ServiceWorkerInstall.component.tsx, packages/context/src/oidc/core/routes/OidcRoutes.tsx, packages/context/src/oidc/vanilla/OidcServiceWorker.js, packages/context/src/oidc/vanilla/initWorker.ts, packages/context/src/oidc/vanilla/oidc.ts
=> fix(firstconexion): reload page on very first login to make serviceworker act as a proxy

MIGRATION_GUIDE_V3_TO_V4.md, packages/context/src/oidc/vanilla/oidc.ts
=> fix(session): session lost on refresh

packages/context/src/App.tsx, packages/context/src/configurations.ts, packages/context/src/oidc/OidcProvider.tsx
=> fix(OidcProvider): missing removeEventSubscription

packages/context/src/oidc/OidcSecure.tsx, packages/context/src/oidc/ReactOidc.tsx, packages/context/src/oidc/vanilla/oidc.ts
#752 does it respond to your need?
=> feat(extra): add extra for login

packages/context/src/oidc/vanilla/OidcServiceWorker.js, packages/context/src/oidc/vanilla/oidc.ts
=> fix(accesstoken): better parsing

packages/context/README.md, packages/context/src/MultiAuth.tsx, packages/context/src/index.tsx, packages/context/src/oidc/OidcProvider.tsx, packages/context/src/oidc/ReactOidc.tsx, packages/context/src/oidc/core/default-component/AuthenticateError.component.tsx, packages/context/src/oidc/core/default-component/Authenticating.component.tsx, packages/context/src/oidc/core/default-component/Callback.component.tsx, packages/context/src/oidc/core/default-component/ComponentTypes.tsx, packages/context/src/oidc/core/default-component/Loading.component.tsx, packages/context/src/oidc/core/default-component/ServiceWorkerInstall.component.tsx, packages/context/src/oidc/core/default-component/ServiceWorkerNotSupported.component.tsx, packages/context/src/oidc/core/default-component/SessionLost.component.tsx, packages/context/src/oidc/vanilla/oidc.ts, packages/context/src/override/AuthenticateError.component.tsx, packages/context/src/override/Authenticating.component.tsx, packages/context/src/override/Callback.component.tsx, packages/context/src/override/Loading.component.tsx, packages/context/src/override/ServiceWorkerNotSupported.component.tsx, packages/context/src/override/SessionLost.component.tsx, packages/context/src/override/style.ts
first iteration to resolve #757
=> feature(sessionlost): add children

.github/workflows/npm-publish.yml, packages/context/README.md, packages/context/package.json, packages/context/src/MultiAuth.tsx, packages/context/src/oidc/OidcProvider.tsx, packages/context/src/oidc/core/default-component/AuthenticateError.component.tsx, packages/context/src/oidc/core/default-component/Authenticating.component.tsx, packages/context/src/oidc/core/default-component/Callback.component.tsx, packages/context/src/oidc/core/default-component/Loading.component.tsx, packages/context/src/oidc/core/default-component/ServiceWorkerInstall.component.tsx, packages/context/src/oidc/core/default-component/ServiceWorkerNotSupported.component.tsx, packages/context/src/oidc/core/default-component/SessionLost.component.tsx, packages/context/src/oidc/core/default-component/SilentCallback.component.tsx, packages/context/src/oidc/vanilla/oidc.ts, packages/context/src/override/AuthenticateError.component.tsx, packages/context/src/override/Authenticating.component.tsx, packages/context/src/override/Callback.component.tsx, packages/context/src/override/Loading.component.tsx, packages/context/src/override/ServiceWorkerNotSupported.component.tsx, packages/context/src/override/SessionLost.component.tsx, readme.md
=> feat(override): add onSessionLostEvent

packages/context/README.md, packages/context/src/Home.tsx, packages/context/src/MultiAuth.tsx, packages/context/src/oidc/ReactOidc.tsx, packages/context/src/oidc/vanilla/oidc.ts
#https://github.com/AxaGuilDEv/react-oidc/issues/713
=> fix(logout): add redirect uri

packages/react/src/App.tsx, packages/react/src/Home.tsx, packages/react/src/oidc/OidcSecure.tsx, packages/react/src/oidc/vanilla/oidc.ts
=> fix(Provider): error better message 

.github/workflows/npm-publish.yml, packages/context/package.json, packages/react/README.md, packages/react/package.json, packages/react/src/oidc/core/default-component/Callback.component.tsx, packages/react/src/oidc/vanilla/oidc.ts, packages/react/src/oidc/vanilla/timer.ts
=> fix(callbakc): Callback does not redirect back to the requested url

packages/react/src/Home.tsx, packages/react/src/oidc/vanilla/oidc.ts
=> fix(logout): allow logout("")

packages/context/package.json, packages/react/src/oidc/vanilla/oidc.ts
=> fix(accesstoken): jwt bad parsing without serviceworker

packages/react/src/Home.tsx, packages/react/src/oidc/OidcSecure.tsx, packages/react/src/oidc/ReactOidc.tsx, packages/react/src/oidc/core/default-component/Callback.component.tsx, packages/react/src/oidc/core/default-component/ServiceWorkerInstall.component.tsx, packages/react/src/oidc/core/default-component/SilentCallback.component.tsx, packages/react/src/oidc/vanilla/initSession.ts, packages/react/src/oidc/vanilla/oidc.ts
=> feat(login): add state property to login and OidcSecure

packages/context/package-lock.json, packages/context/package.json, packages/react/package-lock.json, packages/react/package.json, packages/react/src/App.tsx, packages/react/src/index.tsx, packages/react/src/oidc/OidcProvider.tsx, packages/react/src/oidc/core/default-component/Callback.component.tsx, packages/react/src/oidc/core/routes/OidcRoutes.tsx, packages/react/src/oidc/vanilla/oidc.ts
=> fix(oidc): working with react strict

packages/react/src/oidc/vanilla/oidc.ts
=> fix(callback): promise never resolved

packages/react/README.md, packages/react/src/MultiAuth.tsx, packages/react/src/configurations.ts, packages/react/src/oidc/core/routes/OidcRoutes.tsx, packages/react/src/oidc/vanilla/noHashQueryStringUtils.ts, packages/react/src/oidc/vanilla/oidc.ts
=> feature(hash): no route server

packages/react/src/oidc/vanilla/OidcServiceWorker.js, packages/react/src/oidc/vanilla/oidc.ts
=> fix(token): no refresh token

packages/react/src/App.tsx, packages/react/src/oidc/vanilla/OidcServiceWorker.js, packages/react/src/oidc/vanilla/noHashQueryStringUtils.ts, packages/react/src/oidc/vanilla/oidc.ts
=> fix(hashredirect): more robust

packages/react/src/oidc/core/routes/OidcRoutes.tsx, packages/react/src/oidc/core/routes/route-utils.spec.ts, packages/react/src/oidc/core/routes/route-utils.ts, packages/react/src/oidc/vanilla/oidc.ts
=> fix(hash): callback

packages/react/README.md, packages/react/src/configurations.ts, packages/react/src/oidc/vanilla/initSession.ts, packages/react/src/oidc/vanilla/oidc.ts
=> feat(storage): add way to inject storage

packages/react/src/Home.tsx, packages/react/src/oidc/vanilla/oidc.ts
=> feat(oidclogout): omit post_logout_redirect_uri

packages/react/README.md, packages/react/public/OidcTrustedDomains.js, packages/react/src/Home.tsx, packages/react/src/MultiAuth.tsx, packages/react/src/oidc/ReactOidc.tsx, packages/react/src/oidc/vanilla/OidcTrustedDomains.js, packages/react/src/oidc/vanilla/oidc.ts, readme.md
=> feat(oidc) set up back clean renewTokens

packages/react/src/App.tsx
=> Replace Link with NavLink to show the current Page

packages/react/src/oidc/vanilla/OidcServiceWorker.js, packages/react/src/oidc/vanilla/initSession.ts, packages/react/src/oidc/vanilla/initWorker.ts, packages/react/src/oidc/vanilla/oidc.ts, packages/react/src/oidc/vanilla/parseTokens.ts
=> feat(oidc): add nonce check

packages/react/src/oidc/vanilla/OidcServiceWorker.js, packages/react/src/oidc/vanilla/initWorker.ts, packages/react/src/oidc/vanilla/oidc.ts, packages/react/src/oidc/vanilla/parseTokens.ts
=> fix(oidc): no refresh token rotation

.github/workflows/npm-publish.yml, packages/react/package-lock.json, packages/react/package.json, packages/react/src/MultiAuth.tsx, packages/react/src/configurations.ts, packages/react/src/oidc/OidcSecure.tsx, packages/react/src/oidc/ReactOidc.tsx, packages/react/src/oidc/core/default-component/SilentLogin.component.tsx, packages/react/src/oidc/vanilla/oidc.ts
=> feat(login): add silentLogin from existing oidc session

packages/react/src/oidc/vanilla/initSession.ts, packages/react/src/oidc/vanilla/oidc.ts
fix for #831 @fffan64 at AXA Japan ^^
=> fix(oidc): case when nonce is given on a token refresh

packages/react/src/oidc/vanilla/initWorker.ts
=> fix(nextjs): navigator undefined with SSR

.github/workflows/npm-publish.yml, packages/react/package.json, packages/react/tsconfig.json
=> fix(oidc): npm package should not be shipped with typescript files

packages/react/src/oidc/vanilla/OidcServiceWorker.js, packages/react/src/oidc/vanilla/parseTokens.ts
=> fix(oidc): better parse token jwt

packages/react/src/oidc/vanilla/OidcServiceWorker.js
closes #865 
The service worker would always validate trusted domains, it doesn't have support for a wildcard.
The service worker can now accept a wildcard trusted domain to automatically accept any domain (this includes the hasToSendTokens check aswell as the checkDomain checks)
=> Allow service worker to accept any domain

packages/react/package.json
=> fix(sourcemap): add scr back

.github/workflows/npm-publish.yml, packages/react/src/oidc/vanilla/initWorker.ts
=> fix(oidc): ServiceWorker errors

MIGRATION_GUIDE_V3_TO_V4.md
Migration guide Fix prop type `authenticatingComponent`
=> docs(Migration): Update MIGRATION_GUIDE_V3_TO_V4.md

.prettierrc.json, CONTRIBUTING.md, MIGRATION_GUIDE_V3_TO_V4.md, MIGRATION_GUIDE_V3_TO_V5.md, MIGRATION_GUIDE_V4_TO_V5.md, MIGRATION_GUIDE_V5_TO_V6.md, packages/react/README.md
- Contributing.md  direct user to packages/react (instead of packages/context) as of v6
- Migration guide, minor formatting and tidy.
- Readme, HTML->MD , md lint run.
- add Prettier lint rules for quotes
=> docs(Readme): Minor updates to docs.

.github/workflows/azure-static-web-apps-black-rock-0dc6b0d03.yml, .github/workflows/azure-static-web-apps-icy-glacier-004ab4303.yml, packages/react/config/defaultEslintConfig.js, packages/vanilla-demo/src/index.tsx
=> fix(demo):  deployment

.github/workflows/npm-publish.yml, packages/react/src/oidc/vanilla/oidc.ts
=> fix(oidc): token not refreshed when hidden tab

packages/react/src/oidc/vanilla/oidc.ts
=> fix(oidc): lock when tab hidden on android chrome

packages/react/src/configurations.ts, packages/react/src/oidc/User.ts, packages/react/src/oidc/vanilla/OidcServiceWorker.js, packages/react/src/oidc/vanilla/cache.ts, packages/react/src/oidc/vanilla/oidc.ts, packages/react/src/oidc/vanilla/vanillaOidc.ts, packages/vanilla-demo/src/index.tsx, packages/vanilla/README.md
=> doc(vanilla): write readme

packages/react/src/oidc/vanilla/route-utils.spec.ts, packages/react/src/oidc/vanilla/route-utils.ts
Small PullRequest to resolve #919 use case
=> feat(oidc): accept multiple protocol

packages/react/src/oidc/vanilla/route-utils.ts
=> fix(oidc): multi protocol

packages/react/README.md, packages/react/src/MultiAuth.tsx, packages/react/src/configurations.ts, packages/react/src/oidc/vanilla/initSession.ts, packages/react/src/oidc/vanilla/initWorker.ts, packages/react/src/oidc/vanilla/oidc.ts
First fix off #916
Will be cleanner and safer in another pullrequest
=> fix(oidc): get login params null and crash when tab open

packages/nextjs-demo/package-lock.json, packages/nextjs-demo/package.json, packages/react/src/oidc/vanilla/checkSession.ts, packages/react/src/oidc/vanilla/login.ts, packages/vanilla-demo/package-lock.json, packages/vanilla-demo/package.json
=> fix(oidc): single logout

packages/react/src/oidc/vanilla/oidc.ts, packages/vanilla-demo/package-lock.json, packages/vanilla-demo/package.json
=> fix(oidc): refresh after retries

readme.md
Should resolve https://github.com/AxaGuilDEv/react-oidc/issues/865
=> docs: Mention usage of wildcard '*' for Trusted domains.

readme.md
=> docs(readme): Minor tidy, reduce code indenting (for small screens)

.github/workflows/npm-publish.yml, .gitignore, packages/nextjs-demo/package-lock.json, packages/nextjs-demo/package.json, packages/react/package.json, packages/react/tsconfig.json, packages/vanilla-demo/package-lock.json, packages/vanilla-demo/package.json
=> fix(packages): set back ComonJS

packages/react/src/oidc/FetchToken.tsx
=> fix(oidc): null error when no valid token is somehow present

packages/react/src/oidc/vanilla/parseTokens.ts
=> fix(oidc): do not wait when not auth

packages/react/src/oidc/vanilla/oidc.ts
try to fix #1039 by initializing timer
=> fix(oidc): coordinated token renewal when multiple tabs visible

packages/react/src/oidc/FetchToken.tsx
=> fix(react-oidc): add useCallback for fetch function to memoized it

packages/react/src/oidc/vanilla/requests.ts
=> fix(oidc): Abord request is never handled

packages/react/README.md, packages/react/service_worker/OidcServiceWorker.ts, packages/react/src/MultiAuth.tsx, packages/react/src/oidc/OidcProvider.tsx, packages/react/src/oidc/vanilla/oidc.ts, packages/react/src/oidc/vanilla/requests.ts, packages/react/src/oidc/vanilla/vanillaOidc.ts, packages/vanilla/README.md
=> feat(oidc): fetch can be injected

readme.md
=> fix(readme): typo in example

packages/react/src/oidc/core/routes/OidcRoutes.tsx
=> fix(oidc-react): defaultProps deprecated in function component

.github/workflows/azure-static-web-apps-black-rock-0dc6b0d03.yml, .github/workflows/azure-static-web-apps-icy-glacier-004ab4303.yml, packages/oidc-client/bin/post-install.mjs, packages/react-oidc/bin/post-install.mjs
=> fix(ci): website and ci

packages/oidc-client-service-worker/src/OidcServiceWorker.ts
=> fix: improper token revocation when logging out and showAccessToken=true

.eslintignore, .eslintrc.cjs, examples/nextjs-demo/components/layout.js, examples/nextjs-demo/pages/_app.js, examples/nextjs-demo/pages/index.js, examples/oidc-client-demo/src/index.tsx, examples/react-oidc-demo/src/App.spec.tsx, examples/react-oidc-demo/src/App.tsx, examples/react-oidc-demo/src/FetchUser.tsx, examples/react-oidc-demo/src/Home.tsx, examples/react-oidc-demo/src/MultiAuth.tsx, examples/react-oidc-demo/src/Profile.tsx, examples/react-oidc-demo/src/override/SessionLost.component.tsx, examples/react-oidc-demo/src/utils/sleep.ts, examples/react-oidc-demo/src/utils/timer.ts
- Add utils required for react-oidc-demo spec test. (possibly broke in workspace refactor)
=> refactor(lint): Enable linting on examples folder , fix lint warnings.

examples/oidc-client-demo/package.json, examples/oidc-client-demo/src/index.tsx, examples/react-oidc-demo/README.md, examples/react-oidc-demo/package.json, package.json, packages/oidc-client/README.md, packages/oidc-client/package.json, packages/react-oidc/package.json, packages/react-oidc/src/FetchToken.tsx, packages/react-oidc/src/OidcProvider.tsx, packages/react-oidc/src/OidcSecure.tsx, packages/react-oidc/src/ReactOidc.tsx, packages/react-oidc/src/User.ts, packages/react-oidc/src/core/default-component/Callback.component.tsx, packages/react-oidc/src/core/default-component/SilentCallback.component.tsx, packages/react-oidc/src/core/default-component/SilentLogin.component.tsx, packages/react-oidc/src/core/routes/OidcRoutes.tsx, packages/react-oidc/src/index.ts, pnpm-lock.yaml, readme.md
Rename @axa-fr/vanilla-oidc to @axa-fr/oidc-client for more clarity.
=> feat(oidc): rename vanilla-oidc to oidc-client

CONTRIBUTING.md, FAQ.md, MIGRATION_GUIDE_V6_TO_V7.md, examples/oidc-client-demo/src/index.tsx, packages/oidc-client/README.md, packages/oidc-client/src/index.ts, packages/oidc-client/src/oidcClient.ts, packages/react-oidc/README.md, packages/react-oidc/src/FetchToken.tsx, packages/react-oidc/src/OidcProvider.tsx, packages/react-oidc/src/OidcSecure.tsx, packages/react-oidc/src/ReactOidc.tsx, packages/react-oidc/src/User.ts, packages/react-oidc/src/core/default-component/Callback.component.tsx, packages/react-oidc/src/core/default-component/SilentCallback.component.tsx, packages/react-oidc/src/core/default-component/SilentLogin.component.tsx, pnpm-lock.yaml, readme.md
BREAKING CHANGE: VanillaOidc Renamed OidcClient
@axa-fr/vanilla-oidc renamed @axa-fr/oidc-client
=> feat(oidc): rename repository oidc-client

packages/oidc-client/src/oidc.ts
=> fix(oidc): parent instead of top for iframe allow app inside iframe (alpha)

packages/oidc-client-service-worker/src/OidcServiceWorker.ts
=> fix(oidc-service-worker): gracefull timeout on firefox (alpha)

.github/workflows/azure-static-web-apps-black-rock-0dc6b0d03.yml, .github/workflows/azure-static-web-apps-icy-glacier-004ab4303.yml, packages/oidc-client-service-worker/src/OidcServiceWorker.ts, packages/oidc-client-service-worker/src/types.ts, packages/oidc-client-service-worker/src/utils/__tests__/domains.spec.ts, packages/oidc-client-service-worker/src/utils/__tests__/testHelper.ts, packages/oidc-client/README.md, packages/oidc-client/src/initWorker.ts, packages/react-oidc/README.md
=> fix(oidc): clean link with service worker

packages/oidc-client-service-worker/src/OidcServiceWorker.ts
=> feat(service-worker): add to trusted type (alpha)

examples/oidc-client-demo/public/staticwebapp.config.json, examples/react-oidc-demo/public/staticwebapp.config.json, packages/oidc-client/README.md, packages/oidc-client/src/index.ts, packages/oidc-client/src/initWorker.ts, packages/oidc-client/src/location.ts, packages/oidc-client/src/login.ts, packages/oidc-client/src/logout.spec.ts, packages/oidc-client/src/logout.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/oidcClient.ts, packages/oidc-client/src/requests.ts, packages/react-oidc/README.md, packages/react-oidc/src/OidcProvider.tsx, packages/react-oidc/src/core/routes/OidcRoutes.tsx
=> feat(oidc): make location injectable (alpha)

packages/oidc-client/README.md, packages/oidc-client/src/fetch.ts, packages/oidc-client/src/oidcClient.ts, packages/oidc-client/src/user.ts, packages/react-oidc/src/FetchToken.tsx
=> feat(oidc-client): move fetch to oidc-client

packages/oidc-client/README.md, packages/oidc-client/src/iniWorker.spec.ts, packages/oidc-client/src/initWorker.ts, packages/oidc-client/src/initWorkerOption.ts, packages/oidc-client/src/login.ts, packages/oidc-client/src/logout.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/renewTokens.ts, packages/oidc-client/src/types.ts, packages/react-oidc/README.md
=> feat(oidc-client): enhance service worker flexibility (alpha)

packages/oidc-client/src/logout.ts
=> fix(logout): okta tokens null (alpha)

.github/dependabot.yml
=> fix(ci): Update dependabot.yml to run monthly

packages/oidc-client/README.md, packages/oidc-client/src/initWorker.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/parseTokens.ts, packages/oidc-client/src/types.ts, packages/oidc-client/src/user.ts, packages/react-oidc/README.md
=> feat(oidc-client): allow to take control on service-worker registration (alpha)

examples/react-oidc-demo/src/configurations.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/renewTokens.ts
=> fix(oidc): sessions storage renew tokens (alpha)

packages/oidc-client/src/renewTokens.ts
=> fix: make locks work only ifAvailable

packages/oidc-client/src/oidc.ts, packages/oidc-client/src/renewTokens.ts
=> fix(oidc): session storage for next

packages/oidc-client/src/events.ts, packages/oidc-client/src/renewTokens.ts
=> fix(oidc): temp renew token fix

packages/oidc-client/src/initWorkerOption.ts
=> fix(oidc): crash when regex on userAgent empty result iOS

packages/oidc-client/src/login.ts
=> fix(oidc): Handling of errors returned from authorize endpoint

examples/react-oidc-demo/public/OidcTrustedDomains.js, examples/react-oidc-demo/src/FetchUser.tsx, examples/react-oidc-demo/src/MultiAuth.tsx, packages/oidc-client/README.md, packages/oidc-client/src/checkSession.ts, packages/oidc-client/src/initSession.ts, packages/oidc-client/src/initWorker.ts, packages/oidc-client/src/jwt.ts, packages/oidc-client/src/keepSession.ts, packages/oidc-client/src/login.ts, packages/oidc-client/src/logout.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/parseTokens.ts, packages/oidc-client/src/renewTokens.ts, packages/oidc-client/src/requests.ts, packages/oidc-client/src/types.ts, packages/oidc-client/src/user.ts, packages/react-oidc/README.md, readme.md
=> feat(oidc): DPOP configuration 

examples/react-oidc-demo/index.html, examples/react-oidc-demo/src/MultiAuth.tsx, examples/react-oidc-demo/src/configurations.ts, packages/oidc-client/src/keepSession.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/renewTokens.ts, packages/oidc-client/src/silentLogin.ts
=> refactor(renew): clean an debug (alpha)

packages/oidc-client/src/initSession.ts, packages/oidc-client/src/oidc.ts
=> fix(oidc): json not valid (alpha)

packages/oidc-client/src/checkSession.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/renewTokens.ts, packages/oidc-client/src/requests.ts, packages/oidc-client/src/silentLogin.ts
=> fix(oidc): eternal lock when refresh_token invalid and multiple tabs

packages/react-oidc/src/ReactOidc.tsx
=> feat(react): expose dpop method generation

examples/react-oidc-demo/src/Home.tsx, packages/oidc-client/README.md, packages/oidc-client/src/logout.spec.ts, packages/oidc-client/src/logout.ts, packages/oidc-client/src/oidc.ts
=> feat(oidc): logout add extras parameter to avoid the page reload (alpha)

packages/oidc-client/package.json, packages/oidc-client/src/crypto.ts, packages/oidc-client/src/jwt.ts, pnpm-lock.yaml
=> refactor(oidc): remove base64.js dependency

packages/oidc-client/README.md, packages/oidc-client/src/logout.spec.ts, packages/oidc-client/src/logout.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/requests.ts
=> feat(oidc): add extras to revoke access_token and refresh_tokens

packages/react-oidc/src/User.ts
=> fix(oidc): unload user on logout

packages/oidc-client/src/location.ts
this pullrequest should fix
#1298
=> fix(oidc): logout continue to run before redirecting (alpha)

packages/oidc-client-service-worker/src/utils/__tests__/tokens.spec.ts, packages/oidc-client-service-worker/src/utils/tokens.ts, packages/oidc-client/src/parseTokens.spec.ts, packages/oidc-client/src/parseTokens.ts
=> fix(oidc): parse token with many _ or -

examples/react-oidc-demo/src/configurations.ts, packages/oidc-client/README.md, packages/oidc-client/src/events.ts, packages/oidc-client/src/fetch.ts, packages/oidc-client/src/index.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/parseTokens.spec.ts, packages/oidc-client/src/parseTokens.ts, packages/oidc-client/src/renewTokens.ts, packages/oidc-client/src/types.ts, packages/oidc-client/src/user.ts, packages/react-oidc/README.md, packages/react-oidc/src/ReactOidc.tsx, packages/react-oidc/src/User.ts, packages/react-oidc/src/index.ts
=> feature(oidc): token renew only when required (alpha)

examples/react-oidc-demo/public/OidcTrustedDomains.js, packages/oidc-client-service-worker/src/OidcServiceWorker.ts, packages/oidc-client-service-worker/src/dpop.ts, packages/oidc-client-service-worker/src/types.ts, packages/oidc-client-service-worker/src/utils/__tests__/domains.spec.ts, packages/oidc-client-service-worker/src/utils/__tests__/testHelper.ts, packages/oidc-client/README.md, packages/oidc-client/src/fetch.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/oidcClient.ts, packages/oidc-client/src/user.ts, packages/react-oidc/README.md, packages/react-oidc/src/FetchToken.tsx, packages/react-oidc/src/User.ts
=> feat(oidc): control dpop injection (alpha)

README.md, examples/react-oidc-demo/package.json, packages/react-oidc/vite.config.ts, pnpm-lock.yaml
test to resolve  https://github.com/AxaFrance/oidc-client/issues/1370
=> fix(react-oidc): compatibility with react 19 (alpha)

packages/oidc-client/src/renewTokens.ts
=> fix(oidc): session lost to quickly (alpha)

packages/oidc-client/src/initWorker.ts
fix for https://github.com/AxaFrance/oidc-client/issues/1395
=> fix(oidc): MessageChannel is not closed after message is received (release)

packages/oidc-client-service-worker/src/OidcServiceWorker.ts
Refactor OidcServiceWorker to use null coalescing.
=> refactor(oidc): null coalescing

packages/oidc-client-service-worker/src/OidcServiceWorker.ts, packages/oidc-client-service-worker/src/__tests__/oidcConfig.spec.ts, packages/oidc-client-service-worker/src/oidcConfig.ts
Extract `GetCurrentDatabaseTokenEndpoint` to own file, add test coverage.
=> refactor (oidcServiceWorker): Extract GetCurrentDatabaseTokenEndpoint, add tests

eslint.config.mjs, packages/oidc-client/src/fetch.ts, packages/oidc-client/src/login.ts, packages/oidc-client/src/silentLogin.ts
- Exclude `prettierrc.cjs` from lint
- lint prettier format autofix and adjust signature of Function
- null coalescing chain.
=> chore(lint): Fix lint warnings. (release)

packages/oidc-client/src/initWorker.ts
=> Fix usage of config option service_worker_register
