AxaFrance/oidc-client

examples/context/package.json, packages/context/src/Context/AuthenticationContext.container.js, packages/context/src/Context/AuthenticationContext.container.spec.js, packages/context/src/Services/oidcServices.js
After a silent failure, token expired is stuck in his own state. Login is no longer possible
Login  with a expired token possible + silentsignin when token expired
Close #77
=> fix token expired event

package-lock.json, packages/context/package.json
react-router is used in the package [@axa-fr/react-oidc-context](https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/context#readme).
https://github.com/AxaGuilDEv/react-oidc/blob/c9ef58e7c2e328b30d9cd6e8201ffd462809f5e7/packages/context/src/Routes/AuthenticationRoutes.js#L2
However it's not listed as a dependency in the project.
=> fix(react-oidc-context) Add react-router to dependencies

package-lock.json, package.json
Main issue is referenced in detail here: https://github.com/AxaGuilDEv/react-oidc/issues/148
Jest 24+ requires Babel 7 (see here: https://jestjs.io/docs/en/getting-started#babel-6)
Your library is currently using Babel 6, and therefore the tests are all failing. I thought simply locking Jest down to version 23 would be the quickest fix for this issue, and then a core maintainer can look into upgrading to Babel 7 when and if the time comes.
Tests broken: 
Tests fixed:
=> fix(deps): fix failing tests by locking down the version of Jest to Major 23.* branch

packages/context/README.md, packages/context/src/Callback/Callback.container.js, packages/context/src/Callback/Callback.container.spec.js, packages/context/src/Context/AuthenticationContext.container.js, packages/context/src/Context/AuthenticationContext.js, packages/context/src/Routes/AuthenticationRoutes.js, packages/context/src/Routes/OidcRoutes.js, packages/context/src/Routes/OidcRoutes.spec.js, packages/context/src/Routes/__snapshots__/AuthenticationRoutes.spec.js.snap, packages/redux/README.md, packages/redux/src/AuthenticationCallback.js, packages/redux/src/AuthenticationRoutes.js, packages/redux/src/Oidc.js, packages/redux/src/OidcRoutes.js
Hello again!
This one is an English correction. We wouldn't refer to something as "not authentified", the correct term would be "not authenticated". I've done a search and replace here to replace all instances. It all seems to work fine for me, but please do check it.
I realise this will also change one of the routes, but this is worth it as it's correct English. Hope this is ok!
Routes and props that were not authenticated were referred to as "not authentified".
These routes and props are using the term "not authenticated".
=> English - change all instances of "authentified" to be "authenticated"

examples/redux/src/index.js
undefined <= 0 will **always** be false in javascript
if the configuration is empty, the exception gets thrown as expected.
=> fix typo to get the condition working

examples/context/package-lock.json, examples/context/package.json, examples/context/src/ie.polyfills.js, examples/context/src/index.js, examples/redux/package-lock.json, examples/vanilla/package-lock.json, package-lock.json, packages/context/README.md, packages/core/src/routes/__snapshots__/withRouter.spec.js.snap, packages/core/src/routes/withRouter.js, packages/core/src/routes/withRouter.spec.js, packages/redux/README.md, packages/redux/src/AuthenticationCallback.js, packages/redux/src/Oidc.js
=> fix(router) : Add some polyfills for IE

packages/context/README.md, packages/context/src/Context/AuthenticationContext.container.js, packages/core/src/routes/OidcRoutes.js, packages/redux/README.md, packages/redux/src/AuthenticationCallback.js, packages/redux/src/Oidc.js
=> Fix component prop type validation to use elementType

packages/context/API.md, packages/context/README.md
Couple of minor self-explanatory wording and typo fixes for the documentation.
=> doc(context): fix minor typos in readme

packages/context/src/oidcContext/AuthenticationContext.hooks.spec.ts, packages/context/src/oidcContext/AuthenticationContext.hooks.ts, packages/context/src/oidcContext/AuthenticationContext.provider.tsx, packages/context/src/oidcContext/AuthenticationContext.tsx, packages/context/src/reactServices/OidcSecure.tsx
When performing a disconnection, an authentication was restarted
An authentication was launched during the disconnection
Additional action allowing a dispatch which launches the disconnection action properly
=> fix: add logout action

examples/context/src/Pages/Admin/Admin.jsx, examples/context/src/Router/Routes.js, examples/context/src/configuration.js, packages/context/src/reactServices/OidcSecure.tsx
Doesnt Memoize Component, each change in React OIDC rerender the child Component (during silent renew for example)
The child component is memoized. The silent renew doesnt rerender the component inside.
Closes #450
=> fix(context): Memoize the child component

examples/redux/src/App.js, packages/redux/README.md, packages/redux/src/OidcSecure.tsx
> Please note, some unrelated changes are due to project Prettier config that input singleQuote and trailing comma
=> feat(react-oidc-redux): Adding Redux Authenticating component

packages/vanilla/src/index.js
The `signinSilentCallback` doesn't return the object 
```javascript
{
type: "callback"
}
```
=> fix(Vanilla): return type callback with signinSilent

packages/context/src/oidcContext/AuthenticationContext.provider.tsx
Typescript throws errors when when a partial configuration is served to the AuthenticationProvider.
This should fix #472
Suggested by @ghostd in https://github.com/AxaGuilDEv/react-oidc/pull/457#issuecomment-644894640_
=> fix(context): made type for AuthenticationProviderProps partial

packages/core/src/services/oidcServices.spec.ts, packages/core/src/services/oidcServices.ts
When accessing a protected route with a hash part in the URL, the hash part is lost in the URL where we are redirected.
For example, when accessing http://mywebsite.com/#/tasks/tasks-list, we are redirected to http://mywebsite.com/ after login.
This is especially an issue when we use a "HashRouter" and all the routing is managed thanks to the hash part of the URL.
The hash part is kept in the URL that is sent to the identity server in the state, and we are redirected successully to the initial route. For example, when accessing http://mywebsite.com/#/tasks/tasks-list, we are redirected to http://mywebsite.com/#/tasks/tasks-list after login.
=> fix(core): keep location.hash in the url used to redirect after login

packages/context/package-lock.json, packages/context/package.json, packages/core/package-lock.json, packages/core/package.json, packages/redux/package-lock.json, packages/redux/package.json
Packages *context*, *core* & *redux* use **prop-types** as dependency but when you want to uses these packages, you must add **prop-types** dependency  into your project.
In some case, isn't necessary & **prop-types** doc recommand to include it as dependencies.
https://github.com/facebook/prop-types#how-to-depend-on-this-package
=> Add prop-types as dependency

examples/context/src/Pages/SimpleComponent/index.js, packages/core/src/services/authenticationService.ts, packages/core/src/services/loggerService.ts
On each call to Oauth2 server into a browser, we have a debug console entry that contains all configuration.
But for security it's better to not expose debug console entry into production (pentests result recommendation).
First I try to change into main component **AuthenticationProvider** but it doesn't change anythings. This is cause by call order of logger init & authentication.
So my PR remove this debug console entry. We can discuss to find a better solution.
=> Delete logger debug for overriden configuration

packages/context/src/oidcContext/AuthenticationContext.hooks.spec.ts, packages/context/src/oidcContext/AuthenticationContext.hooks.ts, packages/context/src/oidcContext/AuthenticationContext.provider.tsx
Closes #415
```js
<AuthenticationProvider
configuration={oidcConfiguration}
loggerLevel={oidcLog.DEBUG}
isEnabled={true}
callbackComponentOverride={CustomCallback}
UserStore={InMemoryWebStorage}
>
```
```js
<AuthenticationProvider
configuration={oidcConfiguration}
loggerLevel={oidcLog.DEBUG}
isEnabled={true}
callbackComponentOverride={CustomCallback}
UserStore={InMemoryWebStorage}
customEvents={{
onUserLoaded: (user) => console.log('onUserLoaded', user),
onUserUnloaded: () => console.log('onUserUnloaded'),
onSilentRenewError: (error) => console.log('onSilentRenewError', error),
onUserSignedOut: () => console.log('onUserSignedOut'),
onUserSessionChanged: () => console.log('onUserSessionChanged'),
onAccessTokenExpiring: () => console.log('onAccessTokenExpiring'),
onAccessTokenExpired: () => …
```
=> feat(context): Allowing hooking into the oidc-client events in the AuthenticationProvider

CONTRIBUTING.md, azure-pipelines.yml, package.json, packages/context/src/oidcContext/AuthenticationContext.provider.spec.tsx, packages/context/src/oidcContext/AuthenticationContext.provider.tsx, packages/core/src/index.ts
Used by [Tokgen](https://github.com/youf-olivier/tokgen) We have ann issue when unmounting the provider. The userManager persists.
We have to set the userManager to null when the provider is unmounted to be able te configure it with another configuration set
I also simplified the install script.
=> feat: unload userManager when unmount oidc provider

.github/dependabot.yml
chore is deprecated, so I am trying to change the prefix to build
=> ci: add dependabot config file and change prefix to `build(npm)`

examples/redux/src/App.js, examples/redux/src/configuration.js, examples/redux/src/index.js, packages/redux/README.md, packages/redux/src/Oidc.spec.tsx, packages/redux/src/Oidc.tsx, packages/redux/src/OidcSecure.tsx, packages/redux/src/__snapshots__/Oidc.spec.tsx.snap
fix #403 issue
- OidcSecure.tsx : remove isLoading to harmonize the code with the oidc context package
- Oidc.tsx : make usermanager retrieval synchronous 
- it remains to take into account the <Oidc> isEnabled property to disable authorization properly when set to false (i will fix this in another PR)
=> fix(redux): create usermanager before rendering + some refacto

packages/context/src/oidc/vanilla/initWorker.ts
Make the keepAlive call relative to origin instead  being relative to the current Page.
The url https://mydomain.com/page1/section1 will result in a call to https://mydomain.com/page1/OidcKeepAliveServiceWorker.json
The url https://mydomain.com/page1/section1 will result in a call to https://mydomain.com/OidcKeepAliveServiceWorker.json
=> [fix] Make the keepAlive call relative to origin

packages/context/README.md, packages/context/package-lock.json, packages/context/src/Home.tsx, packages/context/src/MultiAuth.tsx, packages/context/src/Profile.tsx, packages/context/src/oidc/ReactOidc.tsx, packages/context/src/oidc/User.ts
Hey there! Love this library, it's really neat, huge props! 🎉 
This PR attempts to decouple the information from the `useOidcUser()` hook. I am aware that I can use the `withOidcSecure()` hook to secure a component to check if the user is authenticated or not and redirect to the login page. However, the latter is not useful when I'm dealing with multiple libraries for different providers (e.g., I use the [`msal-react`](https://www.npmjs.com/package/@azure/msal-react) library for Azure sign-in alongside this one for other on-prem identity providers like IdentityServer or CAS Apereo).
I'm decoupling because `useOidcUser()` causes unnecessary re-renders when I only want to know if the user is authenticated or not. This greatly  impacts the performance of my application currently, especially …
=> refactor(hook): Decoupling user authenticated flag on hook call

packages/react/README.md, packages/react/src/oidc/OidcProvider.tsx, packages/react/src/oidc/core/default-component/Callback.component.tsx, packages/react/src/oidc/core/routes/OidcRoutes.tsx, packages/react/src/oidc/core/routes/withRouter.tsx, packages/react/src/oidc/vanilla/timer.ts
Could not use **react-oidc** in ***NextJS*** based application, because ***Server Side Rendering*** (aka ***SSR***) would fail on `undefined` reference to `window`.
Additionally, on redirect back to the ***NextJS*** application, the final redirect would not work properly, the router would not detect the URL/History changes. 
In NodeJS the window object does not exists, the global object is the closes alternative. When **react-oidc** is executed on the server side (in Node JS), it uses `global` object conditionally instead of `window`.
When returning back from the IDP, the default URL/History modification is not detected by ***NextJS*** router. The `CallbackManager` has been extended to allow an externally defined custom history object witch implements the `replaceState` method. By …
=> feat(oidc): NextJS  Compatibility

packages/context/package.json
Source maps don't really work if the files that they refer to are not present in the package.
This change brings the context package in line with the react package, which correctly includes the `src` directory.
This was originally addressed as part of #741, but the change seems to have been reversed in 403f28d0e1ad121bc4fbf7f76ee381c98a120d8f.
=> Add source code to context package

packages/react/src/oidc/OidcProvider.tsx
Semicolon would occur after login errors in output.
Semicolon will not occur after login errors in output.
=> fix(oidcprovider): remove semicolon from error output

packages/react/src/oidc/FetchToken.tsx, packages/react/src/oidc/vanilla/OidcServiceWorker.js
The type of the fetch object that `useOidFetch` exposes does not match the type signature of the global `fetch` function, which makes it a bit difficult to make wrapper hooks (or other things) on top of this fetch instance.
By using typescript to extract the parameters of the global `fetch` type and passing them back into `fetchWithToken` it keeps the method signature identical, after that we can use the spread syntax to expand the parameters back into the original requested arguments.
=> fix(type): Expose fetch type from "useOidcFetch" correctly

packages/context/tsconfig.json, packages/react/package.json, packages/react/tsconfig.json, packages/vanilla/tsconfig.json
- set jsx type to `react-jsx` (https://stackoverflow.com/questions/67776707/ts-config-jsx-reactjsx-vs-react)
- remove `npm i` call from package.json `build`, should not be required.
=> task(config): Set jsx type to "react-jsx".  Remove npm i task in build

packages/react/src/oidc/vanilla/OidcServiceWorker.js
Error message to show correct filename `OidcTrustedDomains.js` instead of `TrustedDomains.js`
Aligns to actual filename in repository.
thrown Error would show
```text
is not trusted, please add domain in TrustedDomains.js
```
```text
is not trusted, please add domain in OidcTrustedDomains.js
```
=> fix(errorMessages): Error message to show correct filename

packages/react/src/oidc/vanilla/OidcServiceWorker.js
```
const HOSTS = [
'http://localhost:8080',
new RegExp('(http://[a-zA-Z0-9-]+.abc.com/users/)', 'g'),
new RegExp('(https://[a-zA-Z0-9-]+.xyz.app/api/)', 'g'),
];
const trustedDomains = {
default: HOSTS,
config_classic: HOSTS,
}
```
A better way to go about is also to make everything as regex (internally to support backwards compatibility) and get rid of the 2 step if-else condition.
=> feat(regex-domain-support): update oidcserviceworker to support regex match

packages/react/src/oidc/vanilla/OidcServiceWorker.js, readme.md
"JavaScript [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) objects are stateful when they have the [global](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global) or [sticky](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky) flags"
Since the g flag was used in regex, it caused matches to fail everytime the regex was run. If your client had a higher time set for refreshing access token, the first request would fail and the rest would succeed. And if the time to refresh access token is shorter, all the requests would fail with a 401.
Reason: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test
=> fix: remove global regex and use without flags

packages/react/README.md, packages/react/src/oidc/vanilla/OidcServiceWorker.js, packages/react/src/oidc/vanilla/types.ts
#791  - Adding ability to convert service worker upgrades to use cors mode. This allows correct token processing for requests that are not cors initially, e.g. coming from img tags or download links.
When you try to show images that require authentication to access service worker was not able to attach authorization header because request was non-cors and it only allows simple headers.
We can configure to upgrade all requests service worker intercepts to cors mode.
=> feat(oidc): Adding ability to convert all service worker requests to cors

packages/react/src/oidc/vanilla/requests.ts
other functions (e.g. performRevocationRequestAsync) were calling internalFetch and passing timeoutMs as 3rd parameter, but it was taken as numberRetry
`internalFetch` was defined as
```ts
const internalFetch = async (url, headers, numberRetry = 0, timeoutMs = 10000) => {
...
```
functions like `performTokenRequestAsync` were calling internalFetch like 
```ts
const response = await internalFetch(url, {
method: 'POST',
headers: {
'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
},
body: formBodyString,
}, timeoutMs);
// ^ 3rd param is numberRetry
```
swapped `internalFetch` parameters to get
```ts
const internalFetch = async (url, headers, timeoutMs = 10000, numberRetry = 0) => {
...
```
now timeoutMs is in the right place
=> fix(oidc): wrong parameter order for internalFetch

packages/react/src/oidc/vanilla/vanillaOidc.ts
When adding groups as scope to oidc settings file, the OidcUserInfo is missing this attribute
=> fix(oidc): Add missing groups attribute

packages/react/src/oidc/vanilla/vanillaOidc.ts
Fix lint error
```js
src\oidc\vanilla\vanillaOidc.ts
Line 98:22:  Expected a semicolon  @typescript-eslint/member-delimiter-style
```
=> fix: lint error missing semicolon

packages/react/service_worker/.eslintrc.js, packages/react/service_worker/OidcServiceWorker.ts, packages/react/service_worker/tsconfig.json
Improve the types in OidcSerivceWorker
@guillaume-chervet  Could you please look at the below lines.  I've had to ts-ignore two of the lines because of invalid return types. Is what is there correct or needs review?
The forced type assertion may just need a review of the types not to be null.
```js
// forced type assertion, could be null?
200: const { isValid, reason } = isTokensOidcValid(tokens, nonce, currentDatabaseElement.oidcServerConfiguration as OidcServerConfiguration); 
399: return fetchPromise.then(hideTokens(currentDatabase as OidcConfig));
//expects promise, but is void response
343: event.waitUntil(event.respondWith(fetch(newRequest)));
444: event.waitUntil(event.respondWith(maPromesse));
```
can these be written as
```ts
event.waitUntil(fetch(newRequest)); …
```
=> refactor(types): Improve types in OidcServiceWorker. 

readme.md
Add note about configuring wildcards for `oidctrusteddomains.js` and caution against using them.
- minor linting to the readme.
Should resolve #865
=> docs(oidctrusteddomains): Add note about configuring wildcards for trusteddomains

packages/react/src/oidc/vanilla/initWorker.ts
Ensure the prop `oidcConfiguration.service_worker_convert_all_requests_to_cors`  is copied when constructing oidcConfiguration
May resolve #982 and #974 (when configured with the prop set true)
Question: What should the `default` value `service_worker_convert_all_requests_to_cors` ?
Setting it true would avoid the error being reported, would that be considered the default/preferred configuration?
=> fix(serviceworker): Copy prop service_worker_convert_all_requests_to_cors

packages/react/tsconfig.json
- Error issue introduced in e128be41573e158cc052e6ae1f08805adbcca058 when changed package.json to module but typescript still emit commonJS format.
This change sets typescript module type is ESModules so it emits to match package.json `"type":"module"`
React package will throw error `exports is not defined. in fetchtoken
Described error should be resolved.
=> fix(modules): Fix issue with compilation of react package to ESmodules format

packages/react/src/App.tsx, packages/react/src/oidc/FetchToken.tsx, packages/react/src/oidc/OidcProvider.tsx, packages/react/src/oidc/OidcSecure.tsx, packages/react/src/oidc/ReactOidc.tsx, packages/react/src/oidc/User.ts, packages/react/src/oidc/core/default-component/Callback.component.tsx, packages/react/src/oidc/core/default-component/SilentCallback.component.tsx, packages/react/src/oidc/core/default-component/SilentLogin.component.tsx, packages/react/src/oidc/core/default-component/index.ts, packages/react/src/oidc/core/routes/OidcRoutes.tsx, packages/react/src/oidc/index.ts, packages/react/src/oidc/vanilla/checkSession.ts, packages/react/src/oidc/vanilla/index.ts, packages/react/src/oidc/vanilla/initWorker.ts, packages/react/src/oidc/vanilla/login.ts, packages/react/src/oidc/vanilla/logout.ts, packages/react/src/oidc/vanilla/oidc.ts, packages/react/src/oidc/vanilla/parseTokens.ts, packages/react/src/oidc/vanilla/renewTokens.ts, packages/react/src/oidc/vanilla/requests.ts, packages/react/src/oidc/vanilla/silentLogin.ts, packages/react/src/oidc/vanilla/user.ts, packages/react/src/oidc/vanilla/vanillaOidc.ts, packages/react/src/override/AuthenticateError.component.tsx, packages/react/src/override/Callback.component.tsx, packages/react/src/override/Loading.component.tsx, packages/react/src/override/ServiceWorkerNotSupported.component.tsx, packages/react/src/override/SessionLost.component.tsx
When `module: ESNext` was introduced in 26c150be3222541bb8e3071c339843137ed9a845 it has broken imports for consumers.
Causing issues described in #1006 
If I understand correctly  https://github.com/microsoft/TypeScript/issues/42151  imports for esmodules should be written with a `.js` extension (there is also a recommendation to set this as the default in vscode etc) , as tsc (by design ?) will not alter import statements in .ts files even when tsconfig is `module: esnext`, 
This PR updates all the imports to have the .js extension.
- https://github.com/Zoltu/typescript-transformer-append-js-extension
=> fix(react): Fix issue where imports not found due to missing .js extension

.github/workflows/azure-static-web-apps-icy-glacier-004ab4303.yml, .github/workflows/npm-publish.yml
hi @jafin , this is not perfect but it should allow to run unit test from fork pullrequest.
We may set up a working branch in order to autodeploy demo and alpha-beta after a merge.
=> fix(ci): skip task with secrets from for PullRequest

packages/react/vite.serviceWorker.config.js
Resolve issue #1016 by updating Vite service worker config to output CommonJS instead of ES.
Since the migration of the `OidcServiceWorker.js` code to TypeScript, there is no `OidcServiceWorker.js` file being generated, instead we have an ES module called `OidcServiceWorker.mjs` instead. This means the `copy.cjs` script silently fails to copy the script over to the `public` folder because of this code:
```
const serviceworkerFilePath = path.join(__dirname, "..", "dist/service_worker", serviceworkerFilename);
if (fs.existsSync(serviceworkerFilePath)) {
...
```
We get a `OidcServiceWorker.js` in the `dist` folder and the `copy.cjs` script should work as before.
=> Resolve issue #1016 by updating Vite service worker config

packages/react/service_worker/OidcServiceWorker.ts
Imagine you have mapped your API in a subpath of your application:
- Your App: https://my-domain/
- Your API: https://my-domain/my-api/
The library can handle it well so far. The application makes an ajax request to the API and the ServiceWorker intercepts it and inserts the correct headers.
In a scenario in which the tokens are managed in cookies, you can also call the API endpoints directly in your browser after authentication. E.g. with https://my-domain/my-api/endpoint-with-get-request
The browser would send automatically the cookie and everything would be fine.
This doesn't seem to work with this library and I was wondering why.
I found that where the original request is exchanged and the headers with the tokens are inserted is the trouble spot:
```js
const newRequest = new …
```
=> fix(oidc): ServiceWorker Correct handling of requests with mode "navigate"

packages/react/src/oidc/vanilla/checkSession.ts
The scope was hardcoded in the startCheckSessionAsync function to "openid".
This causes an issue where when we retrieve the token, the scope was only for openid.
I changed the hardcoded scope to use the scopes from the configuration (eg.: configuration.scope)
=> Change the openid hardcoded scope to use the configuration scope

packages/vanilla-demo/src/index.tsx
`getFetch` is `private getFetch: () => Fetch;`, which means it should be a function that returns `fetch`, not `fetch` itself.
If you try to run `vanilla-demo` using the local `@axa-fr/vanilla-oidc`, it will throw with "fetch is not a function":
```sh
cd packages/react
npm run i
cd ..
cd vanilla
npm run i
npm link
cd ..
cd vanilla-demo
npm run i
npm link @axa-fr/vanilla-oidc
npm run start
```
=> fix(vanilla-demo): proper fetch injection

.github/workflows/npm-publish.yml, CONTRIBUTING.md
Packages are automaticaly published on npm when a PR is merged on main.
Example of commit messages :
To publish a patch version (0.0.x) :
- fix(oidc): my message (alpha) => will publish next patch as an alpha
- chore(oidc): my message (beta) => will publish next patch as an beta
- refactor(oidc): my message (release) => will publish next patch release (with automatic git tag and release)
To publish a minor version (0.x.0) :
- feat(oidc): my message (alpha) => will publish next minor as an alpha
- feat(oidc): my message (beta) => will publish next minor as an beta
- feat(oidc): my message (release) => will publish next minor release (with automatic git tag and release)
To publish a major version (x.0.0) :
- fix(oidc): my message containing BREACKING word (alpha) => will publish next major …
=> chore(ci): add way to publish alpha, beta, release (alpha)

.github/workflows/npm-publish.yml
Introduce a period between the `alpha|version` meta tag and the `build number`.
Although not strictly semver (they appear to use a +) apparently NPM will strip the + metadata though so that is not ideal.
It appears common for libs to use the format  `x.xxx-beta.xx`
This change aligns to that format.
Version would be `1.4.0-alpha5`
Version will be `1.4.0-alpha.5`
=> ci(version): Add a period between version alpha|beta and run_number

packages/oidc-client-service-worker/src/OidcServiceWorker.ts, packages/oidc-client/public/OidcServiceWorker.js, packages/oidc-client/src/initWorker.ts
Detecting situation when service worker installed but does not control application(this is valid situation after hard refresh) and reclaiming control in response. Since this has to be done from within service worker itself have to send separate message to it.
After Hard refresh we lose Bearer token injection for request. As a result you get 401 for most of request.
All works smooth
should fix #1098
=> Reclaming all clients from SW after hard reload

packages/oidc-client-service-worker/src/utils/__tests__/domains.spec.ts, packages/oidc-client-service-worker/src/utils/domains.ts
=> fix: add URL normalization for getCurrentDatabaseDomain endpoints comparison

packages/oidc-client-service-worker/src/utils/__tests__/tokens.spec.ts, packages/oidc-client-service-worker/src/utils/tokens.ts, packages/oidc-client/src/parseTokens.spec.ts, packages/oidc-client/src/parseTokens.ts
=> fix(oidc): parseJwt fails for some JWT because of wrong use of replace (alpha)

examples/react-oidc-demo/public/OidcTrustedDomains.js, examples/react-oidc-demo/public/staticwebapp.config.json, examples/react-oidc-demo/src/Home.tsx, examples/react-oidc-demo/vite.config.js, packages/oidc-client-service-worker/src/OidcServiceWorker.ts, packages/oidc-client-service-worker/src/crypto.ts, packages/oidc-client-service-worker/src/dpop.ts, packages/oidc-client-service-worker/src/jwt.ts, packages/oidc-client-service-worker/src/types.ts, packages/oidc-client-service-worker/src/utils/__tests__/domains.spec.ts, packages/oidc-client-service-worker/src/utils/__tests__/testHelper.ts, packages/oidc-client-service-worker/src/utils/__tests__/tokens.spec.ts, packages/oidc-client-service-worker/src/utils/domains.ts, packages/oidc-client-service-worker/src/utils/tokens.ts, packages/oidc-client/README.md, packages/oidc-client/src/login.ts, packages/oidc-client/src/oidc.ts, packages/react-oidc/README.md
=> feat(oidc): dpop inside serviceworker

packages/oidc-client/src/silentLogin.ts
=> fix(oidc): when having multiple iframes, only the last one gets resolved

packages/oidc-client-service-worker/src/utils/__tests__/domains.spec.ts, packages/oidc-client-service-worker/src/utils/domains.ts
User info with port will not replace the access token.
User info with port will now properly forward the access token.
=> fix: normalize userinfo endpoint in service worker

examples/react-oidc-demo/src/Profile.tsx, examples/react-oidc-demo/src/configurations.ts, packages/oidc-client/src/keepSession.ts, packages/oidc-client/src/login.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/oidcClient.ts, packages/oidc-client/src/types.ts, packages/react-oidc/src/User.ts
=> feature(oidc):preload user (alpha)

.github/workflows/azure-static-web-apps-black-rock-0dc6b0d03.yml, .github/workflows/azure-static-web-apps-icy-glacier-004ab4303.yml, .github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/npm-publish.yml, package.json, packages/oidc-client/package.json, packages/react-oidc/package.json
- Update github actions to later versions (avoids the deprecated warning with node 18)
- Set Node version to `20` (from `18`) in pipeline
- modify test action in `package.json` to run in non-watch mode, so tests can be triggered from root workspace with `pnpm test` . 
- simplify pipeline to just be `pnpm test`
=> build(pipeline): Update actions to non-deprecated versions. bump node version to 20.  Run tests in non-wait mode

examples/react-oidc-demo/src/Profile.tsx
`classname` may have accidently been modified to `contaicner` fixed with `container`.
=> fix (demo): fix 'container' classname.

packages/oidc-client/src/oidcClient.ts, packages/react-oidc/src/FetchToken.tsx
Change type of param to boolean (default: false) to resolve compile error:
```text
packages/react-oidc prepare: src/FetchToken.tsx:12:48 - error TS2345: Argument of type 'boolean' is not assignable to parameter of type 'false'.
packages/react-oidc prepare: 12   const newFetch = oidc.fetchWithTokens(fetch, demonstrating_proof_of_possession);
```
https://github.com/AxaFrance/oidc-client/actions/runs/9913967120/job/27392088934#step:6:121
=> fix (FetchToken): Fix FetchToken param to be boolean instead of false (release)

.github/workflows/azure-static-web-apps-black-rock-0dc6b0d03.yml, .github/workflows/azure-static-web-apps-icy-glacier-004ab4303.yml, .github/workflows/ci.yml, .github/workflows/npm-publish.yml
- Updates job agents to v4, earlier versions are marked deprecated
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3, actions/setup-node@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Note: This does not cover `CI.yml`, as that has been done in lint PR.
=> build(job): Update job scripts to v4. (earlier versions are marked deprecated)

packages/oidc-client-service-worker/src/utils/__tests__/domains.spec.ts
Tests are verifying no exception is thrown, not that the response is void. Changed to be more explicit about intent.
=> tests(domain): Be more explicit about intent of test

eslint.config.mjs
Fix Eslint to run prettier.
The existing eslint config is incorrect and was not running the prettier validation rules.
This fails the lint step now and is expected, since all the prettier violations are detected.  PR #1416 should resolve them.
=> fix(eslint): Fix ESLint to run prettier

packages/oidc-client/src/events.ts, packages/oidc-client/src/initWorker.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/renewTokens.ts, packages/oidc-client/src/silentLogin.ts, packages/react-oidc/src/ReactOidc.tsx
- fix spelling `token_acquired`
- refactor(parameters): Default parameters should be last.sonarlint(typescript:S1788)
- refactor(initWorker): null coalescing
this will be a breaking change if consumers reference `eventNames.token_aquired`
=> Minor refactor , possible breaking change for eventNames.token_aquired rename

packages/oidc-client-service-worker/src/OidcServiceWorker.ts, packages/oidc-client-service-worker/src/__tests__/oidcConfig.spec.ts, packages/oidc-client-service-worker/src/types.ts, packages/oidc-client-service-worker/src/utils/__tests__/domains.spec.ts, packages/oidc-client-service-worker/src/utils/__tests__/testHelper.ts
Fix from https://github.com/AxaFrance/oidc-client/pull/1402 has one issue - if `allowMultiTabLogin` flag is true and second tab is opened (when first tab is already authenticated), trying to initiate token renewal (using refresh token) from second tab fails. This is because previously tabId was saved to database only when login flow was initiated from given tab. This fix adds registering of tab id each time service worker receives `init` event.
=> fix(oidc): record tabIds when service worker receives init event (release)

packages/react-oidc/src/ReactOidc.tsx
The TS2322 error occurs in `ReactOidc.tsx` because the type of the extras parameter only accepts `StringMap`. 
I think it should include `null` as a union.
The TS2322 error occurs in `ReactOidc.tsx`
will prevent the error from occurring
=> fix(oidc): Add null as union type into arguments for login, logout, renewTokens

packages/react-oidc/src/ReactOidc.tsx
I've modified default value as null for `extras` parameters in login, logout, renewTokens  https://github.com/AxaFrance/oidc-client/pull/1427
But I realized that they shoud be `undefined` because loginAsync,logoutAsync,renewTokensAsync accept `extras` as option.
TS2345 erro occur in `ReactOidc.tsx`
will prevent the error from occurring
=> fix(oidc): Add undefined as union type into arguments for login, logout, renewTokens

packages/oidc-client-service-worker/src/OidcServiceWorker.ts, packages/oidc-client/src/initWorker.ts
If you have `allowMultiTabLogin` and you have few tabs opened, you can face issue with logout function.
As I found, after logout there are still couple of messages sent from client to serwiceWorker (init and setState, at least).
This leads to case, when `currentDatabase.state` is changed after you passed logout function, but before you get redirected back to login screen. (At lease I think this is a reason. If you have better ideas about how to fix this - please comment, this is interesting).
So when you try to login after logout, you receive 400 error from OAuth2 server, because client sends request with some data from previous session (which was closed obviously).
You can loggin back to app from any tab without errors
=> fix(logout): should work correctly with multiple tabs (release)

packages/oidc-client/src/initWorker.ts, packages/oidc-client/src/keepSession.ts, packages/oidc-client/src/login.ts, packages/oidc-client/src/logout.ts, packages/oidc-client/src/oidc.ts, packages/oidc-client/src/renewTokens.ts
This is a follow-up for https://github.com/AxaFrance/oidc-client/pull/1423. Mechanism introduced in https://github.com/AxaFrance/oidc-client/pull/1402 works under assumption that session storage for each tab is independent and opening new tab creates fresh instance of it. Which is generally true, except for one browser gimmick - if page is duplicated (in Chrome -> right click on tab name then "Duplicate") session storage is copied to duplicated tab (see https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage). This creates an issue in following scenario:
1. User opens application and logs in
2. User duplicates tab 
3. User logs out from both tabs
4. User tries to log in again on both tabs
This scenario can cause various issues, depending on specific IDP, which are caused by …
=> fix(oidc): ensure unique tabIds when page is duplicated (release)

examples/react-oidc-demo/package.json, packages/oidc-client/src/initWorker.ts
Should help with https://github.com/AxaFrance/oidc-client/issues/1400
Also allow to update SW when some code changes happens within same version. At lest existing `service_worker_update_require_callback` was effective enough for me in private app tests and with react-oidc-demo app too. I didn't fail in any reload loop, since SW copy function was added to app prestart.
@piotrbartnik  @guillaume-chervet  would be great if you could prove that it works or not at yours environment
=> fix(oidc): force sw update when new registration appears (release)

packages/oidc-client/package.json, packages/oidc-client/src/renewTokens.ts
Users who leave the application running in the background and subsequently lose VPN connectivity are generating excessive "Failed to fetch" errors in our observability logs. This issue arises because the application does not transition to the "Session Lost" state as expected, due to a flaw in the synchroniseTokensAsync function. Properly handling this scenario by moving affected sessions to the "Session Lost" state would mitigate unnecessary error logging.
The synchroniseTokensAsync function in renewTokens.ts could enter an infinite loop when an error occurred during token renewal, as recursive calls to itself were made without a proper break  incrementing the "index" variable when the window document is hidden.
The implementation now prevents infinite recursion in synchroniseTokensAsync …
=> fix(renewTokens): prevent infinite loop on renew token flow

packages/oidc-client/src/initSession.ts
When using localStorage as the session storage, the userInfo stays present even after logging out. Due to this and with the recent addition of caching, invalid data gets eventually loaded from the localStorage (as there is no validation on load) and will display wrong information in some cases (e.g. user has switched account on the IdP).
=> Clear userInfo in storage in clearAsync function
